var a=" Hello Iam JavaScript "
console.log(a.length)
//console.log(Math.round(Math.random()*1000))
console.log(a.split(" "))
console.log(a.charAt(5))
console.log(a.concat("hello"))
console.log(a.endsWith(" "))
console.log(a.endsWith("t"))
console.log(a.includes("Iam "))
console.log(a.indexOf("H"))
console.log(a.lastIndexOf("p"))
console.log(a.replace("l","a"))
console.log(a.repeat(2))
console.log(a.trim())